spring.application.name=session

spring.datasource.url=jdbc:mysql://localhost:3306/usersession
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=10m
